# -------------------------
# Basic Site Settings
# -------------------------
title          : "Courses website"
title_separator: "-"
name           : &name "Mohammad Mahdi Khorsand Aalam"
description    : &description "Marlik University lecturer (Computer Engineering Department)"
url            : "https://ooiiooiioo.github.io"
baseurl        : "" 
repository     : "https://github.com/OOiiOOiiOO/OOiiOOiiOO.github.io"

# -------------------------
# Languages (multi-lang)
# -------------------------
languages: ["en", "fa"]
default_lang: "en"
exclude_from_localizations: ["assets", "Gemfile", "Gemfile.lock", "node_modules", "vendor"]

# -------------------------
# Author Profile
# -------------------------
author:
  avatar     : "/assets/images/myphoto.jpeg"
  name       : "Mohammad Mahdi Khorsand Aalam"
  bio        : "Marlik University lecturer (Computer Engineering Department)"
  location   : "Iran, Mazandaran , Nowshahr"
  employer   : "Marlik University"
  uri        : "https://marlik.ac.ir"
  email      : "mohammadmahdikhorsandalam@gmail.com" 
  googlescholar: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid        : "http://orcid.org/yourorcidurl"
  pubmed       : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  github       : "academicpages"
  bluesky      : "bsky.app"

# -------------------------
# Collections
# -------------------------
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /news/:path/

# -------------------------
# Defaults for Collections
# -------------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: teaching
    values:
      layout: course
      author_profile: false
      share: false
      comments: false
      breadcrumbs: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

  - scope:
      path: ""
      type: news
    values:
      layout: talk
      author_profile: true
      share: true

# -------------------------
# Plugins
# -------------------------
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-multiple-languages-plugin

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-multiple-languages-plugin

# -------------------------
# Other Settings
# -------------------------
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

permalink: /:categories/:title/
timezone: Etc/UTC

sass:
  sass_dir: _sass
  style: compressed
